---
- hosts: az
  user: ec2-user
  vars:
    site_dir: /usr/share/nginx/html
  tasks:
  - name: upgrade all packages
    yum:
      name: '*'
      state: latest
  - name: Install nginx
    yum:
      name:
        - nginx
      state: latest
  - name: Start nginx
    service:
        name: nginx
        state: started
    become: yes
  - name: Copy the web site
    copy:
      src: ./static-site-src/
      dest: "{{site_dir}}"
    become: yes
  - name: Restart nginx
    service:
      name: nginx
      state: restarted
    become: yes

